vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        activity:
            uri_prefix: /images/activity
            upload_destination: '%kernel.project_dir%/public/images/activity'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
